import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="bg-white dark:bg-black  border-gray-200 dark:border-gray-700">
      <div className="px-6">
        <div className="flex justify-between items-center h-16 relative">
          {/* Left side - Logo */}
          <div className="flex items-center">
            <Link href="/" className="cursor-pointer">
              <h1 className="text-lg font-bold italic text-gray-900 dark:text-white hover:opacity-80 transition-opacity">
                TurboBanana
              </h1>
            </Link>
          </div>

          {/* Right side - Gradient Sphere */}
          <div className="absolute right-0 top-1/2 transform -translate-y-1/2 mr-4">
            <button className="p-1 transition-transform hover:scale-110">
              <div 
                className="w-8 h-8 rounded-full shadow-lg hover:shadow-xl transition-shadow"
                style={{
                  background: 'linear-gradient(180deg, #808080 0%, #EFDA72 19.23%, #DBDBDB 61.54%, #DCDCDC 100%)'
                }}
              ></div>
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexMono.variable} antialiased`}
      >
        <Navbar />
        {/* Three horizontal lines below navbar */}
        <div>
          <div className="h-px bg-white mt-0"></div>
          <div className="h-px bg-white mt-1"></div>
          <div className="h-px bg-white mt-4"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
